stages:
  - deploy

build-deploy-code-job:
  stage: deploy
  script: 
  - apt update -y && apt install curl -y
  - cd $HOME
  - echo "Install argo"
  - curl -sLO https://github.com/argoproj/argo-workflows/releases/download/v3.4.1/argo-linux-amd64.gz
  - gunzip argo-linux-amd64.gz
  - chmod +x argo-linux-amd64
  - mv ./argo-linux-amd64 /usr/local/bin/argo
  - argo version --short
  - argo submit /builds/kubefirst/ci/components/argo-gitlab/ci.yaml
